version: '3'

services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - FRONT_END_URL=http://localhost:4200

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 